title: "StackFire Blog"
baseurl: "/blog" # Ruta base del sitio
url: "https://stackfire.github.io" # URL de tu sitio
theme: minima

# Plugins recomendados (opcional)
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
